### ISSUE TITLE
Extremely padded image

### ISSUE THREAD

**Issue by robert-wettstaedt** [alkasm/padded-transformations#4]
I've noticed that under certain circumstances, the image gets padded heavily (by thousands of pixels). 

Here is an example where everything works as expected:

![good-inputs](https://user-images.githubusercontent.com/3035576/51110898-785af300-17fa-11e9-9419-8f875d130277.jpg)
![good-ouput](https://user-images.githubusercontent.com/3035576/51110910-80b32e00-17fa-11e9-9a2a-cff674ca1393.jpg)

And an example where the resulting image is gets padded by 100.000 pixels (notice the bottom right corner in the output):

![bad-inputs](https://user-images.githubusercontent.com/3035576/51110981-a2141a00-17fa-11e9-95a5-4d853fbb2b2d.jpg)
![bad-ouput](https://user-images.githubusercontent.com/3035576/51110983-a5a7a100-17fa-11e9-94fe-01ab3517ab39.jpg)

I was not able to figure out why this is happening, so maybe you could take a look to see what might be going on. I could provide you with the exact values for `M` if you want.

Thanks

**Comment by alkasm** [comment]
@r-wettstaedt Please do share the homography! Sorry I didn't see this sooner---too many GH updates from work clogs my feed @_@

Thank you so much for reporting this. I'll take a look ASAP if you can provide the homography and which function you were using.

**Comment by robert-wettstaedt** [comment]
@alkasm here ist what I did:

```python
src = cv2.imread("./src.jpg")
dst = cv2.imread("./dst.jpg")
M = np.float32([[0.88199074, 0.06742358, -9.91406308],[0.01402804, 0.51202351, -1.23383761],[-0.00599231, -0.00524677, 1.0]])
src_warped, dst_padded = padtransf.warpPerspectivePadded(src, dst, M)
```

I downscaled the images by factor 8, otherwise cv2 might throw an allocation error as the resulting image would be too large.

src: ![image](https://user-images.githubusercontent.com/3035576/51668115-c83b7600-1fc1-11e9-83fa-0eb342bf4592.png)
dst: ![image](https://user-images.githubusercontent.com/3035576/51668122-cb366680-1fc1-11e9-8e94-4d22405a29da.png)

**Comment by alkasm** [comment]
@r-wettstaedt Great, thank you.

> I downscaled the images by factor 8, otherwise cv2 might throw an allocation error as the resulting image would be too large.

I believe this is the issue; you can't use the same homography that relates the larger images for the smaller images. The translation entries (`M[0, 2]` and `M[1, 2]`) and the perspective distortion entries (`M[2, 0]` and `M[2, 1]`) depend on the image size. However, it scales with a nice formula that is really easy to use. See [this SO answer](https://stackoverflow.com/a/48915151/5087436) for a derivation (note, it's math lingo so I think the matrix is transposed from a quick glance). Also, you can see one of my SO answers [here](https://stackoverflow.com/a/45998244/5087436) which partly mentions this scaling.

**Comment by robert-wettstaedt** [comment]
@alkasm yeah that's why I also downscaled the points that build the homography. Usually I would not downscale that whole thing, but the allocation error left me no other choice (which is weird, because last time I tried it, I did not get that error).

You can also try it with the original and unscaled image and points I used:

```python
src = cv2.imread("src.jpg")
dst = cv2.imread("dst.jpg")
s = src.shape

pts1 = np.float32([[88.63637, 16.849434], [526.63635, 4.849434], [31.636368, 762.4858], [315.63635, 594.4858]])
pts2 = np.float32([[0, 0], [s[1], 0], [0, s[0]], [s[1], s[0]]])
M = cv2.getPerspectiveTransform(pts1, pts2)

src_warped, dst_padded = padtransf.warpPerspectivePadded(src, dst, M)
```

src: 
![image](https://user-images.githubusercontent.com/3035576/51672508-f1f99a80-1fcb-11e9-8f8d-9c8f0348332d.png)

dst:
![image](https://user-images.githubusercontent.com/3035576/51672554-089ff180-1fcc-11e9-96f3-196f62ba86ec.png)

**Comment by alkasm** [comment]
FWIW, the following works for me on your small images:

    M = M * np.array([[1, 1, 2], [1, 1, 2], [1/2, 1/2, 1]])**(1/8)
    dst_padded, src_warped = padtransf.warpPerspectivePadded(src, dst, M)

(note you had the return values swapped, probably from my example which is maybe confusing since I'm using the inverse warp flag)

**Comment by alkasm** [comment]
H, ok let me dig into this more.

**Comment by robert-wettstaedt** [comment]
@alkasm Yes, exactly. But why is this happening?

> Also, that memory issue is weird for sure, those images aren't big at all (OpenCV can handle those sized images just fine).

Sure, it handles the downscaled images just fine. The whole process only takes a few milliseconds. But passing the original scaled images in there outputs an image that is 100.000x100.000 pixels or something in these dimensions and takes a few seconds to process.

**Comment by alkasm** [comment]
@r-wettstaedt Yeah I deleted my other comment as even with that description it's still weird. I agree, dividing the points by the scale should be equivalent. It's really late here so I won't be able to dig in more till tomorrow, but thanks again for the report and lmk if you have any findings :)

**Comment by robert-wettstaedt** [comment]
Alright, thanks. Don't worry, I don't need results soon. I worked my way around it by downscaling the images and cropping out the bottom right corner 😅
However, I could provide you with a few more examples of this issue, as I encountered it a few times in my dataset.

**Comment by alkasm** [comment]
@r-wettstaedt that'd be great!

**Comment by robert-wettstaedt** [comment]
@alkasm looks like I was mistaken. I only encountered it two times. The other incident was caused by an almost identical perspective. Maybe it helps finding out what is going on nonetheless.

```python
pts1 = [[80.63637, 42.849434], [508.63635, 6.849434], [54.636368, 777.8494], [329.63635, 588.8494]]
```

src: 
![image](https://user-images.githubusercontent.com/3035576/51707606-f51f7580-2021-11e9-987f-97f483d76072.png)

dst:
![image](https://user-images.githubusercontent.com/3035576/51707668-0f595380-2022-11e9-8eba-a4f6fd0f5127.png)

**Comment by alkasm** [comment]
@r-wettstaedt just to be totally clear, the dst image you provided is the result of using the homography from `getPerspectiveTransform()` with the usual OpenCV `warpPerspective()`, is that correct? Or to put it another way, the homography is definitely fine.

**Comment by robert-wettstaedt** [comment]
@alkasm Yes!

**Comment by alkasm** [comment]
@r-wettstaedt Okay, you just *happened* across a really fun and interesting coincidence. So, homographies map lines to lines, right? And in this case the bottom line of the rock wall gets mapped to the bottom line of the image, and the right side of the rock wall gets mapped to the right side of the image, as expected. However, note what happens to the lines which define the edge of the image in this case. The right side of the image gets mapped to a somewhat diagonal line---the top of that line probably stays close to where it is, but the bottom gets mapped far out to the right. And for the bottom of the image, a similar thing happens...on the left side it's more or less anchored, and on the right side it gets stretched down a ton. In fact, under this particular homography...those lines basically get mapped to parallel lines, meaning the point where they intersect (i.e. the bottom right corner of the image) explodes and goes off towards infinity. Here's mapping the pixel just short of the bottom right corner to the edge of the image, so you can see just how close to parallel the sides become:

![src_warped](https://user-images.githubusercontent.com/9651002/51730129-2c465480-202b-11e9-9782-ef3eb5760274.png)
